- name: Set unprivileged ports sysctl parameter in /etc/sysctl.d/50-UnprivilegedPort.conf
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.d/50-UnprivilegedPort.conf"
    regexp: "^net.ipv4.ip_unprivileged_port_start="
    line: "net.ipv4.ip_unprivileged_port_start={{ host_unprivileged_port_start }}"
    create: true
  notify:
    - Reload sysctl
