- name: Stop quadlet
  ansible.builtin.systemd_service:
    name: "{{ item.name }}"
    state: "stopped"
    scope: "user"
  loop_control:
    label: "{{ item.name}}.service"
  loop: "{{ quadlets }}"
