- name: Stop systemd service
  ansible.builtin.systemd_service:
    name: "{{ item.name }}"
    state: "stopped"
    enabled: false
    scope: "user"
  loop_control:
    label: "{{ item.name}}"
  loop: "{{ containers_systemd }}"
